### ISSUE TITLE
Tasks listed after testacularServer don't run

### ISSUE THREAD

**Issue by jaketrent** [dignifiedquire/grunt-testacular#3]
If I execute a multiple grunt tasks and run testacularServer before other tasks, the remaining grunt tasks are not run.  If my tasks look like this:

```
lint: {
  all: ['**/*.js']
},
testacularServer: {      
  ci: {
    options: {
      keepalive: true
    },
    configFile: 'testacular.conf.js',
    autoWatch: false,
    singleRun: true
  }
}
```

And I run:

```
grunt testacularServer lint
```

Then the `lint` task is never run.

**Comment by dignifiedquire** [comment]
Yes but this is by design. If you want to run tasks after `testacularServer` you need to set `keepalive: false` and use another task at the end of your task list to keep grunt running. So for example you could do something like

``` bash
$ grunt testacularServer lint watch
```

But if you want to use the `keepalive` option `testacularServer` needs to be the last task that is executed.

**Comment by jaketrent** [comment]
Friedel, thanks for the reply.  Your solution to add 'watch' to the end of the task list was the key.  Thank you!
